/*
-- Query: SELECT * FROM dtb_sispen_dev.tbl_professions
LIMIT 0, 1000

-- Date: 2012-06-09 15:53
*/
INSERT INTO tbl_professions (id_profession,name) VALUES (421,'ACOMPANHANTE');
INSERT INTO tbl_professions (id_profession,name) VALUES (422,'AÇOUGUEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (423,'ACUPUNTURISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (424,'ADESTRADOR DE ANIMAIS');
INSERT INTO tbl_professions (id_profession,name) VALUES (425,'ADMINISTRADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (426,'ADMINISTRADOR DE BANCO DE DADOS DBA');
INSERT INTO tbl_professions (id_profession,name) VALUES (427,'ADMINISTRADOR DE REDES');
INSERT INTO tbl_professions (id_profession,name) VALUES (428,'ADMINISTRADOR PÚBLICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (429,'ADVOGADO');
INSERT INTO tbl_professions (id_profession,name) VALUES (430,'AEROMOÇA');
INSERT INTO tbl_professions (id_profession,name) VALUES (431,'AERONAUTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (432,'AEROVIÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (433,'AFIADOR DE FERRAMENTAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (434,'AGENTE COMUNITÁRIO DE SAÚDE');
INSERT INTO tbl_professions (id_profession,name) VALUES (435,'AGENTE DE COMBATE À ENDEMIAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (436,'AGENTE DE DEFESA SANITÁRIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (437,'AGENTE DE DEFESA SANITÁRIA ANIMAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (438,'AGENTE DE VIAGENS');
INSERT INTO tbl_professions (id_profession,name) VALUES (439,'AGENTE FUNERÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (440,'AGENTE PENITENCIÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (441,'AGRICULTOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (442,'AGRIMENSOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (443,'AGRÔNOMO');
INSERT INTO tbl_professions (id_profession,name) VALUES (444,'AJUDANTE DE PRODUÇÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (445,'ALERGOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (446,'ALFAIATE');
INSERT INTO tbl_professions (id_profession,name) VALUES (447,'ALMIRANTE');
INSERT INTO tbl_professions (id_profession,name) VALUES (448,'ALMOXARIFE');
INSERT INTO tbl_professions (id_profession,name) VALUES (449,'ALPINISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (450,'AMBIENTALISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (451,'AMBULANTE');
INSERT INTO tbl_professions (id_profession,name) VALUES (452,'AMOLADOR DE FERRAMENTAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (453,'ANALISTA DE SISTEMAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (454,'ANESTESIOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (455,'ANGIOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (456,'ANTROPÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (457,'APICULTOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (458,'APONTADOR DE MÃO-DE-OBRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (459,'APRESENTADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (460,'ÁRBITRO E MEDIADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (461,'ARGUMENTISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (462,'ARMADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (463,'ARMEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (464,'ARQUEÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (465,'ARQUITETO');
INSERT INTO tbl_professions (id_profession,name) VALUES (466,'ARQUIVISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (467,'ARRANJADOR MUSICAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (468,'ARRUMADEIRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (469,'ARTESÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (470,'ARTISTA DE CIRCO');
INSERT INTO tbl_professions (id_profession,name) VALUES (471,'ARTISTA PLÁSTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (472,'ARTISTA/TÉCNICO EM ESPETÁCULOS DE DIVERSÕES');
INSERT INTO tbl_professions (id_profession,name) VALUES (473,'ASCENSORISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (474,'ASSESSOR DE IMPRENSA');
INSERT INTO tbl_professions (id_profession,name) VALUES (475,'ASSESSOR PARLAMENTAR');
INSERT INTO tbl_professions (id_profession,name) VALUES (476,'ASSISTENTE ADMINISTRATIVO');
INSERT INTO tbl_professions (id_profession,name) VALUES (477,'ASSISTENTE DE CÂMERA');
INSERT INTO tbl_professions (id_profession,name) VALUES (478,'ASSISTENTE DE DIREÇÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (479,'ASSISTENTE DE PRODUÇÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (480,'ASSISTENTE SOCIAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (481,'ASTROFÍSICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (482,'ASTRÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (483,'ASTRONAUTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (484,'ASTRÔNOMO');
INSERT INTO tbl_professions (id_profession,name) VALUES (485,'ATENDENTE');
INSERT INTO tbl_professions (id_profession,name) VALUES (486,'ATLETA DE ARREMESSO DE PESO');
INSERT INTO tbl_professions (id_profession,name) VALUES (487,'ATLETA DE CANOAGEM');
INSERT INTO tbl_professions (id_profession,name) VALUES (488,'ATLETA DE NADO SINCRONIZADO');
INSERT INTO tbl_professions (id_profession,name) VALUES (489,'ATLETA DE TIRO COM ARCO');
INSERT INTO tbl_professions (id_profession,name) VALUES (490,'ATOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (491,'ATUÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (492,'AUDITOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (493,'AUXILIAR ADMINISTRATIVO');
INSERT INTO tbl_professions (id_profession,name) VALUES (494,'AUXILIAR DE REPROGRAFIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (495,'AUXILIAR DE SERVIÇOS GERAIS');
INSERT INTO tbl_professions (id_profession,name) VALUES (496,'AVALISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (497,'AVIADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (498,'BABÁ');
INSERT INTO tbl_professions (id_profession,name) VALUES (499,'BABYSITTER');
INSERT INTO tbl_professions (id_profession,name) VALUES (500,'BAILARINA');
INSERT INTO tbl_professions (id_profession,name) VALUES (501,'BAIXISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (502,'BALCONISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (503,'BANCÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (504,'BARBEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (505,'BARMAN');
INSERT INTO tbl_professions (id_profession,name) VALUES (506,'BARTENDER');
INSERT INTO tbl_professions (id_profession,name) VALUES (507,'BATERISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (508,'BEDEL');
INSERT INTO tbl_professions (id_profession,name) VALUES (509,'BERÇARISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (510,'BIBLIOTECÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (511,'BIBLIOTECONOMISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (512,'BIÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (513,'BIOMÉDICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (514,'BIOQUÍMICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (515,'BIOTECNÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (516,'BÓIA-FRIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (517,'BOMBEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (518,'BORRACHEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (519,'BOTICÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (520,'BOXEADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (521,'BRIGADEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (522,'BROKER/CORRETOR DA BOLSA DE VALORES');
INSERT INTO tbl_professions (id_profession,name) VALUES (523,'CABELEIREIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (524,'CABO');
INSERT INTO tbl_professions (id_profession,name) VALUES (525,'CAÇA-TALENTOS/OLHEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (526,'CADEIRINHA');
INSERT INTO tbl_professions (id_profession,name) VALUES (527,'CADISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (528,'CAIXA');
INSERT INTO tbl_professions (id_profession,name) VALUES (529,'CALDEIREIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (530,'CAMBISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (531,'CAMELÔ');
INSERT INTO tbl_professions (id_profession,name) VALUES (532,'CAMERAMAN');
INSERT INTO tbl_professions (id_profession,name) VALUES (533,'CAMINHONEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (534,'CANCEROLOGISTA OU ONCOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (535,'CANTOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (536,'CAPATAZ');
INSERT INTO tbl_professions (id_profession,name) VALUES (537,'CAPELÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (538,'CAPITÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (539,'CAPOEIRISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (540,'CARDIOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (541,'CARNAVALESCO');
INSERT INTO tbl_professions (id_profession,name) VALUES (542,'CARPINTEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (543,'CARTAZEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (544,'CARTEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (545,'CARTÓGRAFO');
INSERT INTO tbl_professions (id_profession,name) VALUES (546,'CARTUNISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (547,'CATADOR DE CARANGUEIJOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (548,'CATADOR DE MATERIAL RECICLÁVEL');
INSERT INTO tbl_professions (id_profession,name) VALUES (549,'CENÓGRAFO');
INSERT INTO tbl_professions (id_profession,name) VALUES (550,'CENOTÉCNICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (551,'CERAMISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (552,'CERIMONIALISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (553,'CHAPEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (554,'CHARGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (555,'CHAVEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (556,'CHEFE DE COZINHA');
INSERT INTO tbl_professions (id_profession,name) VALUES (557,'CICLISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (558,'CIENTISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (559,'CIENTISTA DA INFORMAÇÃO E DOCUMENTAÇÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (560,'CIENTISTA DE ALIMENTOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (561,'CIENTISTA POLÍTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (562,'CIENTISTA SOCIAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (563,'CINEASTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (564,'CINEGRAFISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (565,'CINEMATOGRÁFO');
INSERT INTO tbl_professions (id_profession,name) VALUES (566,'CIRURGIÃO BUCAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (567,'CIRURGIÃO DENTISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (568,'CLAP LOADER');
INSERT INTO tbl_professions (id_profession,name) VALUES (569,'CLARINETISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (570,'CLASSIFICADOR CONTÁBIL');
INSERT INTO tbl_professions (id_profession,name) VALUES (571,'CLÍNICO GERAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (572,'CO-PILOTO');
INSERT INTO tbl_professions (id_profession,name) VALUES (573,'COACH');
INSERT INTO tbl_professions (id_profession,name) VALUES (574,'COBAIA MÉDICA');
INSERT INTO tbl_professions (id_profession,name) VALUES (575,'COBRADOR DE ÔNIBUS');
INSERT INTO tbl_professions (id_profession,name) VALUES (576,'COBRADOR DE PEDÁGIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (577,'COLOPROCTOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (578,'COMANDANTE');
INSERT INTO tbl_professions (id_profession,name) VALUES (579,'COMERCIANTE');
INSERT INTO tbl_professions (id_profession,name) VALUES (580,'COMISSÁRIO DE BORDO');
INSERT INTO tbl_professions (id_profession,name) VALUES (581,'COMPOSITOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (582,'COMPRADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (583,'CONFEITEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (584,'CONFERENTE DE CARGA E DESCARGA');
INSERT INTO tbl_professions (id_profession,name) VALUES (585,'CONFERENTE DE EXPEDIÇÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (586,'CONFERENTE DE RECEBIMENTO');
INSERT INTO tbl_professions (id_profession,name) VALUES (587,'CONSTRUTOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (588,'CONSULTOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (589,'CONSULTOR DE MODA');
INSERT INTO tbl_professions (id_profession,name) VALUES (590,'CONSULTOR DE RADIESTESIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (591,'CONTÁBIL');
INSERT INTO tbl_professions (id_profession,name) VALUES (592,'CONTABILISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (593,'CONTADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (594,'CONTATÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (595,'CONTINUISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (596,'CONTRA REGRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (597,'CONTRAMESTRE EM TRANSPORTE MARÍTIMO');
INSERT INTO tbl_professions (id_profession,name) VALUES (598,'CONTROLADOR DE VÔO');
INSERT INTO tbl_professions (id_profession,name) VALUES (599,'CONTROLLER');
INSERT INTO tbl_professions (id_profession,name) VALUES (600,'COORDENADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (601,'COPEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (602,'COREÓGRAFO');
INSERT INTO tbl_professions (id_profession,name) VALUES (603,'CORONEL');
INSERT INTO tbl_professions (id_profession,name) VALUES (604,'CORREDOR DE ATLETISMO');
INSERT INTO tbl_professions (id_profession,name) VALUES (605,'CORREGEDOR DE JUSTIÇA');
INSERT INTO tbl_professions (id_profession,name) VALUES (606,'CORRETOR DA BOLSA DE VALORES');
INSERT INTO tbl_professions (id_profession,name) VALUES (607,'CORRETOR DE IMÓVEIS');
INSERT INTO tbl_professions (id_profession,name) VALUES (608,'CORRETOR DE SEGUROS');
INSERT INTO tbl_professions (id_profession,name) VALUES (609,'CORTADOR DE CANA-DE-AÇUCAR');
INSERT INTO tbl_professions (id_profession,name) VALUES (610,'COSTUREIRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (611,'COVEIRO/SEPULTADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (612,'COZINHEIRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (613,'CRÍTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (614,'CUMIM');
INSERT INTO tbl_professions (id_profession,name) VALUES (615,'DANÇARINO');
INSERT INTO tbl_professions (id_profession,name) VALUES (616,'DATILÓGRAFO');
INSERT INTO tbl_professions (id_profession,name) VALUES (617,'DEDETIZADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (618,'DEFENSOR PÚBLICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (619,'DEGUSTADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (620,'DELEGADO');
INSERT INTO tbl_professions (id_profession,name) VALUES (621,'DENTISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (622,'DEPUTADO');
INSERT INTO tbl_professions (id_profession,name) VALUES (623,'DERMATOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (624,'DESEMBARGADOR DE JUSTIÇA');
INSERT INTO tbl_professions (id_profession,name) VALUES (625,'DESENHISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (626,'DESIGNER DE INTERIORES');
INSERT INTO tbl_professions (id_profession,name) VALUES (627,'DESIGNER DE JÓIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (628,'DESIGNER DE MODA');
INSERT INTO tbl_professions (id_profession,name) VALUES (629,'DESIGNER DE PRODUTO OU DESENHISTA INDUSTRIAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (630,'DESIGNER GRÁFICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (631,'DESPACHANTE');
INSERT INTO tbl_professions (id_profession,name) VALUES (632,'DIAGRAMADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (633,'DIALOGUISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (634,'DIARISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (635,'DIGITADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (636,'DIPLOMATA');
INSERT INTO tbl_professions (id_profession,name) VALUES (637,'DIRETOR DE CINEMA');
INSERT INTO tbl_professions (id_profession,name) VALUES (638,'DIRETOR DE FOTOGRAFIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (639,'DIRETOR DE PRODUÇÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (640,'DJ');
INSERT INTO tbl_professions (id_profession,name) VALUES (641,'DOGUEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (642,'DUBLADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (643,'DUBLÊ');
INSERT INTO tbl_professions (id_profession,name) VALUES (644,'ECÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (645,'ECONOMISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (646,'ECONOMISTA DOMÉSTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (647,'EDITOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (648,'EDITOR DE MESA DE CORTE');
INSERT INTO tbl_professions (id_profession,name) VALUES (649,'EDUCADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (650,'EDUCADOR INTEGRADO À SAÚDE PÚBLICA');
INSERT INTO tbl_professions (id_profession,name) VALUES (651,'ELETRICISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (652,'ELETRICISTA DE AUTOMÓVEIS');
INSERT INTO tbl_professions (id_profession,name) VALUES (653,'EMBAIXADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (654,'EMBALADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (655,'EMBALSAMADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (656,'EMPACOTADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (657,'EMPREGADO DOMÉSTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (658,'EMPRESÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (659,'ENCANADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (660,'ENCARREGADO DE MANUTENÇÃO PREDIAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (661,'ENDOCRINOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (662,'ENDODONTISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (663,'ENFERMEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (664,'ENGENHEIRO ACÚSTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (665,'ENGENHEIRO AERONÁUTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (666,'ENGENHEIRO AGRÍCOLA');
INSERT INTO tbl_professions (id_profession,name) VALUES (667,'ENGENHEIRO AGRIMENSOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (771,'ENGENHEIRO AGRÔNOMO');
INSERT INTO tbl_professions (id_profession,name) VALUES (669,'ENGENHEIRO AMBIENTAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (670,'ENGENHEIRO CARTOGRÁFICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (671,'ENGENHEIRO CIVIL');
INSERT INTO tbl_professions (id_profession,name) VALUES (672,'ENGENHEIRO DE ALIMENTOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (673,'ENGENHEIRO DE AQUICULTURA');
INSERT INTO tbl_professions (id_profession,name) VALUES (674,'ENGENHEIRO DE COMPUTAÇÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (675,'ENGENHEIRO DE CONTROLE E AUTOMAÇÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (676,'ENGENHEIRO DE ENERGIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (677,'ENGENHEIRO DE ERGONOMIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (678,'ENGENHEIRO DE HORTICULTURA');
INSERT INTO tbl_professions (id_profession,name) VALUES (679,'ENGENHEIRO DE ILUMINAÇÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (680,'ENGENHEIRO DE MANUFATURA');
INSERT INTO tbl_professions (id_profession,name) VALUES (681,'ENGENHEIRO DE MATERIAIS');
INSERT INTO tbl_professions (id_profession,name) VALUES (682,'ENGENHEIRO DE MINAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (683,'ENGENHEIRO DE PETRÓLEO');
INSERT INTO tbl_professions (id_profession,name) VALUES (684,'ENGENHEIRO DE PROCESSOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (685,'ENGENHEIRO DE PRODUÇÃO AGROINDUSTRIAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (686,'ENGENHEIRO DE PRODUTO OU PRODUÇÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (687,'ENGENHEIRO DE PROJETOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (688,'ENGENHEIRO DE SEGURANÇA DO TRABALHO');
INSERT INTO tbl_professions (id_profession,name) VALUES (689,'ENGENHEIRO DE SOM');
INSERT INTO tbl_professions (id_profession,name) VALUES (690,'ENGENHEIRO DE SUPPLY CHAIN OU LOGÍSTICA');
INSERT INTO tbl_professions (id_profession,name) VALUES (691,'ENGENHEIRO DE TELECOMUNICAÇÕES');
INSERT INTO tbl_professions (id_profession,name) VALUES (692,'ENGENHEIRO DE TRANSPORTES');
INSERT INTO tbl_professions (id_profession,name) VALUES (693,'ENGENHEIRO ELÉTRICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (694,'ENGENHEIRO FÍSICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (695,'ENGENHEIRO FLORESTAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (696,'ENGENHEIRO INDUSTRIAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (697,'ENGENHEIRO MECÂNICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (698,'ENGENHEIRO MECATRÔNICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (699,'ENGENHEIRO METALÚRGICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (700,'ENGENHEIRO NAVAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (701,'ENGENHEIRO PETROQUÍMICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (702,'ENGENHEIRO QUÍMICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (703,'ENGENHEIRO SANITARISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (704,'ENGENHEIRO TÊXTIL');
INSERT INTO tbl_professions (id_profession,name) VALUES (705,'ENGRAXATE');
INSERT INTO tbl_professions (id_profession,name) VALUES (706,'ENÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (707,'ENTALHADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (708,'EPIDEMIÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (709,'ESCOTEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (710,'ESCRITOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (711,'ESCRITURÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (712,'ESCRIVÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (713,'ESCULTOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (714,'ESGRIMISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (715,'ESPECIALISTA EM AGRONEGÓCIOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (716,'ESPELEOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (717,'ESTAMPADOR DE TECIDOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (718,'ESTATÍSTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (719,'ESTETICISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (720,'ESTILISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (721,'ESTIVADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (722,'ESTOFADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (723,'ESTOQUISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (724,'FARMACÊUTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (725,'FATURISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (726,'FAXINEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (727,'FEIRANTE');
INSERT INTO tbl_professions (id_profession,name) VALUES (728,'FERRAMENTEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (729,'FERREIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (730,'FERROVIÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (731,'FIGURANTE');
INSERT INTO tbl_professions (id_profession,name) VALUES (732,'FIGURINISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (733,'FILÓSOFO');
INSERT INTO tbl_professions (id_profession,name) VALUES (734,'FISCAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (735,'FÍSICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (736,'FÍSICO NUCLEAR');
INSERT INTO tbl_professions (id_profession,name) VALUES (737,'FISICULTURISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (738,'FISIOTERAPEUTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (739,'FLANELINHA');
INSERT INTO tbl_professions (id_profession,name) VALUES (740,'FLAUTISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (741,'FLORISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (742,'FONOAUDIÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (743,'FORNEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (744,'FOTÓGRAFO');
INSERT INTO tbl_professions (id_profession,name) VALUES (745,'FRENTISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (746,'FRESADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (747,'FUNDIDOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (748,'FUNDIDOR DE PLACA DE GESSO');
INSERT INTO tbl_professions (id_profession,name) VALUES (749,'FUNILEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (750,'GAGSMAN');
INSERT INTO tbl_professions (id_profession,name) VALUES (751,'GANDULA');
INSERT INTO tbl_professions (id_profession,name) VALUES (752,'GARÇOM');
INSERT INTO tbl_professions (id_profession,name) VALUES (753,'GARI');
INSERT INTO tbl_professions (id_profession,name) VALUES (754,'GARIMPEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (755,'GASTROENTEROLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (756,'GASTRÔNOMO');
INSERT INTO tbl_professions (id_profession,name) VALUES (757,'GENERAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (758,'GEOFÍSICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (759,'GEÓGRAFO');
INSERT INTO tbl_professions (id_profession,name) VALUES (760,'GEÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (761,'GERADORISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (762,'GERENTE DE BANCO');
INSERT INTO tbl_professions (id_profession,name) VALUES (763,'GERENTE DE INOVAÇÕES OU NOVOS NEGÓCIOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (764,'GERENTE DE RISCOS EM SEGUROS');
INSERT INTO tbl_professions (id_profession,name) VALUES (765,'GERENTE DE VENDAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (766,'GERIATRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (767,'GESTOR AMBIENTAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (768,'GESTOR DE QUALIDADE');
INSERT INTO tbl_professions (id_profession,name) VALUES (769,'GESTOR DE RECURSOS HUMANOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (770,'GESTOR DE TECNOLOGIA DA INFORMAÇÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (3,'GESTOR PÚBLICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (4,'GINASTA ARTÍSTICA');
INSERT INTO tbl_professions (id_profession,name) VALUES (5,'GINASTA RÍTMICA');
INSERT INTO tbl_professions (id_profession,name) VALUES (6,'GINECOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (7,'GOURMET');
INSERT INTO tbl_professions (id_profession,name) VALUES (8,'GOVERNADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (9,'GOVERNANTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (10,'GRAFOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (11,'GRAVURISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (12,'GUARDA OU POLICIAL RODOVIÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (13,'GUARDA ROUPEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (14,'GUARDADOR DE VEÍCULOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (15,'GUIA TURISTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (16,'GUINCHEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (17,'GUITARRISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (18,'HARPISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (19,'HEADHUNTER');
INSERT INTO tbl_professions (id_profession,name) VALUES (20,'HEMATOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (21,'HISTORIADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (22,'HOMEOPATA');
INSERT INTO tbl_professions (id_profession,name) VALUES (23,'HOSTESS');
INSERT INTO tbl_professions (id_profession,name) VALUES (24,'ILUSTRADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (25,'IMPLANTODONTISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (26,'IMPRESSOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (27,'IMUNOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (28,'INFECTOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (29,'INSPETOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (30,'INSTALADOR DE LINHA TELEFÔNICA');
INSERT INTO tbl_professions (id_profession,name) VALUES (31,'INSTALADOR DE PAINÉIS');
INSERT INTO tbl_professions (id_profession,name) VALUES (32,'INSTRUMENTADOR CIRÚRGICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (33,'INSTRUMENTISTA MUSICAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (34,'INSTRUTOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (35,'INTÉRPRETE');
INSERT INTO tbl_professions (id_profession,name) VALUES (36,'INTÉRPRETE DE BÍBLIAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (37,'INTÉRPRETE E TRADUTOR DE LÍNGUA DE SINAIS');
INSERT INTO tbl_professions (id_profession,name) VALUES (38,'INVESTIGADOR DE POLÍCIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (39,'INVESTIGADOR PARTICULAR');
INSERT INTO tbl_professions (id_profession,name) VALUES (40,'JANGADEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (41,'JARDINEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (42,'JOGADOR DE BADMINTON');
INSERT INTO tbl_professions (id_profession,name) VALUES (43,'JOGADOR DE BASQUETE');
INSERT INTO tbl_professions (id_profession,name) VALUES (44,'JOGADOR DE BOCHA');
INSERT INTO tbl_professions (id_profession,name) VALUES (45,'JOGADOR DE BOLICHE');
INSERT INTO tbl_professions (id_profession,name) VALUES (46,'JOGADOR DE FUTEBOL');
INSERT INTO tbl_professions (id_profession,name) VALUES (47,'JOGADOR DE GOLFE');
INSERT INTO tbl_professions (id_profession,name) VALUES (48,'JOGADOR DE HANDEBOL');
INSERT INTO tbl_professions (id_profession,name) VALUES (49,'JOGADOR DE HÓQUEI');
INSERT INTO tbl_professions (id_profession,name) VALUES (50,'JOGADOR DE TÊNIS DE MESA');
INSERT INTO tbl_professions (id_profession,name) VALUES (51,'JOGADOR DE VÔLEI');
INSERT INTO tbl_professions (id_profession,name) VALUES (52,'JÓQUEI');
INSERT INTO tbl_professions (id_profession,name) VALUES (53,'JORNALEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (54,'JORNALISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (55,'JUDOCA');
INSERT INTO tbl_professions (id_profession,name) VALUES (56,'JUIZ DE DIREITO');
INSERT INTO tbl_professions (id_profession,name) VALUES (57,'JUIZ DE FUTEBOL');
INSERT INTO tbl_professions (id_profession,name) VALUES (58,'JUIZ OU ÁRBITRO DE FUTEBOL');
INSERT INTO tbl_professions (id_profession,name) VALUES (59,'KARATECA');
INSERT INTO tbl_professions (id_profession,name) VALUES (60,'KITE-SURFER');
INSERT INTO tbl_professions (id_profession,name) VALUES (61,'LABORATORISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (62,'LACTARISTA HOSPITALAR');
INSERT INTO tbl_professions (id_profession,name) VALUES (63,'LAMBOTEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (64,'LANCHEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (65,'LANTERNEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (66,'LAPIDÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (67,'LAVADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (68,'LAVADOR DE VEÍCULOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (69,'LEÃO DE CHÁCARA');
INSERT INTO tbl_professions (id_profession,name) VALUES (70,'LEILOEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (71,'LEITEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (72,'LENHADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (73,'LETRISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (74,'LEVANTADOR DE PESO');
INSERT INTO tbl_professions (id_profession,name) VALUES (75,'LÍDER COMUNITÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (76,'LIMPADOR DE VIDROS');
INSERT INTO tbl_professions (id_profession,name) VALUES (77,'LIXEIRO/COLETOR DE LIXO');
INSERT INTO tbl_professions (id_profession,name) VALUES (78,'LOCUTOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (79,'LUBRIFICADOR DE MÁQUINAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (80,'LUTADOR DE JIU-JITSU');
INSERT INTO tbl_professions (id_profession,name) VALUES (81,'LUTADOR DE KARATÊ');
INSERT INTO tbl_professions (id_profession,name) VALUES (82,'LUTADOR DE KUNG FU');
INSERT INTO tbl_professions (id_profession,name) VALUES (83,'LUTADOR DE LUTA LIVRE');
INSERT INTO tbl_professions (id_profession,name) VALUES (84,'LUTADOR DE TAEKWONDO');
INSERT INTO tbl_professions (id_profession,name) VALUES (85,'LUTHIER');
INSERT INTO tbl_professions (id_profession,name) VALUES (86,'MÃE SOCIAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (87,'MAESTRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (88,'MÁGICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (89,'MAITRE');
INSERT INTO tbl_professions (id_profession,name) VALUES (90,'MAJOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (91,'MANICURE');
INSERT INTO tbl_professions (id_profession,name) VALUES (92,'MANOBRISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (93,'MAQUIADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (94,'MAQUINISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (95,'MARCADOR DE LUZ');
INSERT INTO tbl_professions (id_profession,name) VALUES (96,'MARCENEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (97,'MARECHAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (98,'MARINHEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (99,'MARKETEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (100,'MASSAGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (101,'MASSOTERAPEUTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (102,'MATEMÁTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (103,'MECÂNICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (104,'MECÂNICO DE VÔO');
INSERT INTO tbl_professions (id_profession,name) VALUES (105,'MECANÓGRAFO');
INSERT INTO tbl_professions (id_profession,name) VALUES (106,'MÉDICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (111,'MÉDICO CARDIOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (107,'MÉDICO CIRURGIÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (113,'MÉDICO CLINICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (115,'MÉDICO DO TRABALHO');
INSERT INTO tbl_professions (id_profession,name) VALUES (108,'MÉDICO GENETICISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (109,'MÉDICO LEGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (110,'MÉDICO NUCLEAR');
INSERT INTO tbl_professions (id_profession,name) VALUES (114,'MÉDICO OFTALMOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (112,'MÉDICO PEDIATRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (116,'MEEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (117,'MENSAGEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (118,'MEREDEIRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (119,'MERGULHADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (120,'MESTRE CERVEJEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (121,'MESTRE-DE-OBRAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (122,'METALÚRGICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (123,'METEOROLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (124,'MICROFONISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (125,'MILITAR DA AERONÁUTICA');
INSERT INTO tbl_professions (id_profession,name) VALUES (126,'MILITAR DA MARINHA');
INSERT INTO tbl_professions (id_profession,name) VALUES (127,'MILITAR DO EXÉRCITO');
INSERT INTO tbl_professions (id_profession,name) VALUES (128,'MINISTRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (129,'MODELISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (130,'MODELO');
INSERT INTO tbl_professions (id_profession,name) VALUES (131,'MOLDADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (132,'MOLDUREIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (133,'MOLEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (134,'MONTADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (135,'MONTADOR DE NEGATIVOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (136,'MOTOFRETE');
INSERT INTO tbl_professions (id_profession,name) VALUES (137,'MOTORISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (138,'MOTOTAXISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (139,'MUSEÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (140,'MÚSICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (141,'MUSICOTERAPEUTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (142,'NADADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (143,'NATURÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (144,'NAVEGADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (145,'NECROMAQUIADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (146,'NEFROLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (147,'NEONATOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (148,'NEUROCIRURGIÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (149,'NEUROLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (150,'NOTÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (151,'NUMERÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (152,'NUTRICIONISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (153,'NUTROLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (154,'OBSTETRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (155,'OCEANÓGRAFO');
INSERT INTO tbl_professions (id_profession,name) VALUES (156,'OCULISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (157,'ODONTOLOGISTA ESTÉTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (158,'ODONTOLOGISTA LEGAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (159,'ODONTOLOGISTA PREVENTIVO E SOCIAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (160,'ODONTOPEDIATRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (161,'OFFICE-BOY');
INSERT INTO tbl_professions (id_profession,name) VALUES (162,'OFICIAL DE JUSTIÇA');
INSERT INTO tbl_professions (id_profession,name) VALUES (163,'OFTALMOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (164,'OMBUDSMAN');
INSERT INTO tbl_professions (id_profession,name) VALUES (165,'OPERADOR DE BOMBAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (166,'OPERADOR DE TELEMARKETING');
INSERT INTO tbl_professions (id_profession,name) VALUES (167,'OPERADOR DE VÍDEO');
INSERT INTO tbl_professions (id_profession,name) VALUES (168,'OPTOMETRISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (169,'ORÇAMENTISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (170,'ORIENTADOR EDUCACIONAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (171,'ORTESISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (172,'ORTODONTISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (173,'ORTOPEDISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (174,'ORTOPTISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (175,'OTORRINOLARINGOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (176,'OURIVES');
INSERT INTO tbl_professions (id_profession,name) VALUES (177,'PAGINADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (178,'PAISAGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (179,'PANFLETEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (180,'PANIFICADOR/PADEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (181,'PAPARAZZO');
INSERT INTO tbl_professions (id_profession,name) VALUES (182,'PAPILOSCOPISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (183,'PÁRA-QUEDISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (184,'PARAMÉDICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (185,'PARTEIRA TRADICIONAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (186,'PASSADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (187,'PASTILHEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (188,'PATINADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (189,'PATOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (190,'PATOLOGISTA ORAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (191,'PEÃO DE RODEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (192,'PECUARISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (193,'PEDAGOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (194,'PEDIATRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (195,'PEDICURE');
INSERT INTO tbl_professions (id_profession,name) VALUES (196,'PEDREIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (197,'PEIXEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (198,'PENHORISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (199,'PERCURSIONISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (200,'PERFUMISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (201,'PERFUSIONISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (202,'PERITO CRIMINAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (203,'PERITO JUDICIAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (204,'PERSONAL STYLIST');
INSERT INTO tbl_professions (id_profession,name) VALUES (205,'PERSONAL TRAINER');
INSERT INTO tbl_professions (id_profession,name) VALUES (206,'PESCADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (207,'PESQUISADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (208,'PETROLEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (209,'PIANISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (210,'PILOTO AUTOMOBILÍSTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (211,'PILOTO DE AVIÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (212,'PINTOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (213,'PIZZAIOLO');
INSERT INTO tbl_professions (id_profession,name) VALUES (214,'PLASTIMODELISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (215,'PNEUMOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (216,'PODÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (217,'POLICIAL CIVIL');
INSERT INTO tbl_professions (id_profession,name) VALUES (218,'POLICIAL FEDERAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (219,'POLICIAL MILITAR');
INSERT INTO tbl_professions (id_profession,name) VALUES (220,'POLIDOR DE PRODUÇÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (221,'POLÍTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (222,'PORTEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (223,'PORTUÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (224,'PRÁTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (225,'PREFEITO');
INSERT INTO tbl_professions (id_profession,name) VALUES (226,'PRENSISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (227,'PREPARADOR DE MÁQUINAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (228,'PRESIDENTE DA REPÚBLICA');
INSERT INTO tbl_professions (id_profession,name) VALUES (229,'PROCURADOR DE JUSTIÇA');
INSERT INTO tbl_professions (id_profession,name) VALUES (230,'PRODUTOR DE AUDIO VISUAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (231,'PRODUTOR DE EVENTOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (232,'PRODUTOR DE MULTIMÍDIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (233,'PRODUTOR EDITORIAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (234,'PRODUTOR FONOGRÁFICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (235,'PRODUTOR MUSICAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (236,'PROFESSOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (237,'PROFISSIONAL DE ÁUDIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (238,'PROFISSIONAL DE CINEMA');
INSERT INTO tbl_professions (id_profession,name) VALUES (239,'PROFISSIONAL DE COMÉRCIO EXTERIOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (240,'PROFISSIONAL DE EDUCAÇÃO FÍSICA');
INSERT INTO tbl_professions (id_profession,name) VALUES (241,'PROFISSIONAL DE EFEITOS ESPECIAIS');
INSERT INTO tbl_professions (id_profession,name) VALUES (242,'PROFISSIONAL DE HOTELARIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (243,'PROFISSIONAL DE INFORMÁTICA');
INSERT INTO tbl_professions (id_profession,name) VALUES (244,'PROFISSIONAL DE LINGUÍSTICA');
INSERT INTO tbl_professions (id_profession,name) VALUES (245,'PROFISSIONAL DE LOGÍSTICA');
INSERT INTO tbl_professions (id_profession,name) VALUES (246,'PROFISSIONAL DE MANUTENÇÃO INDUSTRIAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (247,'PROFISSIONAL DE MARKETING');
INSERT INTO tbl_professions (id_profession,name) VALUES (248,'PROFISSIONAL DE RÁDIO E TV');
INSERT INTO tbl_professions (id_profession,name) VALUES (249,'PROFISSIONAL DE RECICLAGEM');
INSERT INTO tbl_professions (id_profession,name) VALUES (250,'PROFISSIONAL DE RECURSOS HUMANOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (251,'PROFISSIONAL DE RELACIONAMENTO COM INVESTIDORES RI');
INSERT INTO tbl_professions (id_profession,name) VALUES (252,'PROFISSIONAL DE RELAÇÕES INTERNACIONAIS');
INSERT INTO tbl_professions (id_profession,name) VALUES (253,'PROFISSIONAL DE RELAÇÕES PÚBLICAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (254,'PROFISSIONAL DE TECNOLOGIA DE LATICÍNIOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (255,'PROGRAMADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (260,'PROGRAMADOR .NET');
INSERT INTO tbl_professions (id_profession,name) VALUES (261,'PROGRAMADOR ASP');
INSERT INTO tbl_professions (id_profession,name) VALUES (259,'PROGRAMADOR C#');
INSERT INTO tbl_professions (id_profession,name) VALUES (267,'PROGRAMADOR C++');
INSERT INTO tbl_professions (id_profession,name) VALUES (266,'PROGRAMADOR COBOL');
INSERT INTO tbl_professions (id_profession,name) VALUES (256,'PROGRAMADOR DE COMPUTADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (265,'PROGRAMADOR HTML 5');
INSERT INTO tbl_professions (id_profession,name) VALUES (258,'PROGRAMADOR JAVA');
INSERT INTO tbl_professions (id_profession,name) VALUES (263,'PROGRAMADOR PASCAL - DELPHI');
INSERT INTO tbl_professions (id_profession,name) VALUES (262,'PROGRAMADOR VB');
INSERT INTO tbl_professions (id_profession,name) VALUES (264,'PROGRAMADORJAVASCRIPT');
INSERT INTO tbl_professions (id_profession,name) VALUES (257,'PROGRAMADORPHP');
INSERT INTO tbl_professions (id_profession,name) VALUES (268,'PROJETISTA MECÂNICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (269,'PROMOTOR DE EVENTOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (270,'PROMOTOR DE VENDAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (271,'PROMOTOR PÚBLICO/DE JUSTIÇA');
INSERT INTO tbl_professions (id_profession,name) VALUES (272,'PROTESISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (273,'PROTÉTICO DENTÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (274,'PSICÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (275,'PSICOMOTRICISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (276,'PSICOPEDAGOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (277,'PSIQUIATRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (278,'PUBLICITÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (279,'QUADRINISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (280,'QUÍMICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (281,'QUÍMICO FARMACÊUTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (282,'QUIROPRAXISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (283,'QUITANDEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (284,'RADIALISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (285,'RADIALISTA PROGRAMADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (286,'RADIOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (287,'RADIOOPERADOR DE VÔO');
INSERT INTO tbl_professions (id_profession,name) VALUES (288,'RADIOTERAPÊUTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (289,'REBARBADOR DE METAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (290,'RECEPCIONISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (291,'RECREADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (292,'REDATOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (293,'REGENTE');
INSERT INTO tbl_professions (id_profession,name) VALUES (294,'RELAÇÕES PÚBLICAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (295,'REMADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (296,'REPÓRTER');
INSERT INTO tbl_professions (id_profession,name) VALUES (297,'REPOSITOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (298,'REPRESENTANTE COMERCIAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (299,'RESTAURADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (300,'RETIFICADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (301,'REUMATOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (302,'REVENDEDOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (303,'REVISOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (304,'ROTEIRISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (305,'SACOLEIRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (306,'SALGADEIRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (307,'SALVA-VIDAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (308,'SAPATEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (309,'SARGENTO');
INSERT INTO tbl_professions (id_profession,name) VALUES (310,'SAXOFONISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (311,'SECRETÁRIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (312,'SEGUIDOR DE COMPRAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (313,'SEGURANÇA PARTICULAR');
INSERT INTO tbl_professions (id_profession,name) VALUES (314,'SELECIONADOR DE PESSOAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (315,'SENADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (316,'SEPARADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (317,'SERINGUEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (318,'SERRALHEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (319,'SERVENTE-DE-OBRAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (320,'SERVENTUÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (321,'SEXÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (322,'SÍNDICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (323,'SKATISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (324,'SOCIÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (325,'SOLDADO');
INSERT INTO tbl_professions (id_profession,name) VALUES (326,'SOLDADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (327,'SOMELIER');
INSERT INTO tbl_professions (id_profession,name) VALUES (328,'SONOPLASTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (329,'SUBPREFEITO');
INSERT INTO tbl_professions (id_profession,name) VALUES (330,'SUPERVISOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (331,'SURFISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (332,'SUSHIMAN');
INSERT INTO tbl_professions (id_profession,name) VALUES (333,'TABELIÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (334,'TAIFEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (335,'TAPECEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (336,'TATUADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (337,'TAXIDERMISTA/EMBALSAMADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (338,'TAXISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (339,'TECELÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (340,'TÉCNICO DE GESSO');
INSERT INTO tbl_professions (id_profession,name) VALUES (341,'TÉCNICO DE SOM');
INSERT INTO tbl_professions (id_profession,name) VALUES (342,'TÉCNICO EM AGROPECUÁRIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (343,'TÉCNICO EM ARQUIVO');
INSERT INTO tbl_professions (id_profession,name) VALUES (344,'TÉCNICO EM AVIAÇÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (345,'TÉCNICO EM DESPORTO');
INSERT INTO tbl_professions (id_profession,name) VALUES (346,'TÉCNICO EM DOCUMENTAÇÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (347,'TÉCNICO EM EDIFICAÇÕES');
INSERT INTO tbl_professions (id_profession,name) VALUES (348,'TÉCNICO EM HARDWARE');
INSERT INTO tbl_professions (id_profession,name) VALUES (349,'TÉCNICO EM HIGIENE DENTÁRIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (350,'TÉCNICO EM ÓPTICA');
INSERT INTO tbl_professions (id_profession,name) VALUES (351,'TÉCNICO EM RADIOLOGIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (352,'TÉCNICO EM REDE');
INSERT INTO tbl_professions (id_profession,name) VALUES (353,'TÉCNICO EM SEGURANÇA DO TRABALHO');
INSERT INTO tbl_professions (id_profession,name) VALUES (354,'TÉCNICO EM TAQUIGRAFIA');
INSERT INTO tbl_professions (id_profession,name) VALUES (355,'TÉCNICO EM TRATAMENTO DE ÁGUA');
INSERT INTO tbl_professions (id_profession,name) VALUES (356,'TÉCNICO TRIBUTARISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (357,'TECNÓLOGO EM AUTOMAÇÃO INDUSTRIAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (358,'TECNÓLOGO EM CIÊNCIAS DAS PLANTAS MEDICINAIS');
INSERT INTO tbl_professions (id_profession,name) VALUES (359,'TECNÓLOGO EM DESENVOLVIMENTO SOCIAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (360,'TECNÓLOGO EM ESPORTE E LAZER');
INSERT INTO tbl_professions (id_profession,name) VALUES (361,'TECNÓLOGO EM GEOPROCESSAMENTO');
INSERT INTO tbl_professions (id_profession,name) VALUES (362,'TECNÓLOGO EM IRRIGAÇÃO E DRENAGEM');
INSERT INTO tbl_professions (id_profession,name) VALUES (363,'TECNÓLOGO EM JOGOS DIGITAIS');
INSERT INTO tbl_professions (id_profession,name) VALUES (364,'TECNÓLOGO EM NAVEGAÇÃO FLUVIAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (365,'TECNÓLOGO EM NEGÓCIOS IMOBILIÁRIOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (366,'TECNÓLOGO EM PAPEL E CELULOSE');
INSERT INTO tbl_professions (id_profession,name) VALUES (367,'TECNÓLOGO EM PROCESSOS QUÍMICOS');
INSERT INTO tbl_professions (id_profession,name) VALUES (368,'TECNÓLOGO EM PRODUÇÃO DE BEBIDAS');
INSERT INTO tbl_professions (id_profession,name) VALUES (369,'TECNÓLOGO EM PRODUÇÃO MOVELEIRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (370,'TECNÓLOGO EM PRODUÇÃO SUCROALCOOLEIRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (371,'TECNÓLOGO EM RECURSOS PESQUEIROS');
INSERT INTO tbl_professions (id_profession,name) VALUES (372,'TECNÓLOGO EM ROCHAS ORNAMENTAIS');
INSERT INTO tbl_professions (id_profession,name) VALUES (375,'TECNÓLOGO EM SILVICULTURA');
INSERT INTO tbl_professions (id_profession,name) VALUES (373,'TECNÓLOGO EM SISTEMAS DA INFORMAÇÃO');
INSERT INTO tbl_professions (id_profession,name) VALUES (374,'TECNÓLOGO EM SISTEMAS PARA INTERNET');
INSERT INTO tbl_professions (id_profession,name) VALUES (376,'TECNÓLOGO EM TECNOLOGIA DA MADEIRA');
INSERT INTO tbl_professions (id_profession,name) VALUES (377,'TELEFONISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (378,'TELEGRAFISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (379,'TENENTE');
INSERT INTO tbl_professions (id_profession,name) VALUES (380,'TENISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (381,'TEÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (382,'TERAPEUTA FLORAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (383,'TERAPEUTA HOLÍSTICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (384,'TERAPEUTA OCUPACIONAL');
INSERT INTO tbl_professions (id_profession,name) VALUES (385,'TESOUREIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (386,'TIMONEIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (387,'TINTUREIRO');
INSERT INTO tbl_professions (id_profession,name) VALUES (388,'TOPÓGRAFO');
INSERT INTO tbl_professions (id_profession,name) VALUES (389,'TORNEIRO MECÂNICO');
INSERT INTO tbl_professions (id_profession,name) VALUES (390,'TORREIRO/TORRISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (391,'TOSADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (392,'TOXICOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (393,'TRADUTOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (394,'TRANSCRITOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (395,'TRANSPORTADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (396,'TRAUMATOLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (397,'TREINADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (398,'TRIATLETA');
INSERT INTO tbl_professions (id_profession,name) VALUES (399,'TRILHEIRO OU MÚSICO DE CINEMA');
INSERT INTO tbl_professions (id_profession,name) VALUES (400,'TROMPETISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (401,'TURISMÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (402,'UFÓLOGO');
INSERT INTO tbl_professions (id_profession,name) VALUES (403,'URBANISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (404,'UROLOGISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (405,'VELEJADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (406,'VENDEDOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (407,'VENTRÍLOQUO');
INSERT INTO tbl_professions (id_profession,name) VALUES (408,'VEREADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (409,'VETERINÁRIO');
INSERT INTO tbl_professions (id_profession,name) VALUES (410,'VIGIA PARLAMENTAR');
INSERT INTO tbl_professions (id_profession,name) VALUES (411,'VIGILANTE NOTURNO/DIURNO');
INSERT INTO tbl_professions (id_profession,name) VALUES (412,'VIOLONISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (413,'VISTORIADOR DE SINISTROS');
INSERT INTO tbl_professions (id_profession,name) VALUES (414,'VIVEIRISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (415,'WEBDESIGNER');
INSERT INTO tbl_professions (id_profession,name) VALUES (416,'WEBMASTER');
INSERT INTO tbl_professions (id_profession,name) VALUES (417,'WINDSURFER');
INSERT INTO tbl_professions (id_profession,name) VALUES (418,'XILÓGRAFO');
INSERT INTO tbl_professions (id_profession,name) VALUES (419,'ZELADOR');
INSERT INTO tbl_professions (id_profession,name) VALUES (420,'ZOOTECNISTA');
INSERT INTO tbl_professions (id_profession,name) VALUES (421,'NENHUMA');
