/*
-- Query: SELECT * FROM dtb_sispen_dev.tbl_municipalities
LIMIT 0, 1000

-- Date: 2012-06-09 15:39
*/
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (322,'ABADIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (323,'ABAIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (324,'ABARE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (325,'ABELHAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (326,'ABOBORA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (327,'ABRANTES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (328,'ACAJUTIBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (329,'ACU DA TORRE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (330,'ACUDINA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (331,'ACUPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (332,'ADUSTINA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (333,'AFLIGIDOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (334,'AFRANIO PEIXOTO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (335,'AGUA DOCE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (336,'AGUA FRIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (337,'AGUAS DO PAULISTA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (338,'AIQUARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (339,'ALAGOINHAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (340,'ALCOBACA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (341,'ALEGRE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (342,'ALGODAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (343,'ALGODOES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (344,'ALMADINA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (345,'ALTO BONITO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (346,'AMADO BAHIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (347,'AMANIU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (348,'AMARGOSA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (349,'AMELIA RODRIGUES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (350,'AMERICA DOURADA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (351,'AMERICO ALVES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (352,'ANAGE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (353,'ANDARAI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (354,'ANDORINHA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (355,'ANGICAL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (356,'ANGICO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (357,'ANGUERA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (358,'ANTAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (359,'ANTONIO CARDOSO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (360,'ANTONIO GONCALVES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (361,'APORA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (362,'APUAREMA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (363,'ARACAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (364,'ARACATU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (365,'ARACI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (366,'ARAMARI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (367,'ARAPIRANGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (368,'ARATACA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (369,'ARATUIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (370,'AREIAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (371,'AREMBEPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (372,'ARGOIM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (373,'ARGOLO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (374,'ARIBICE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (375,'ARITAGUA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (376,'AURELINO LEAL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (377,'BAIANOPOLIS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (378,'BAIXA DO PALMEIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (379,'BAIXA GRANDE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (380,'BAIXAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (381,'BAIXINHA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (382,'BALUARTE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (383,'BANCO CENTRAL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (384,'BANCO DA VITORIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (385,'BANDEIRA DO ALMADA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (386,'BANDEIRA DO COLONIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (387,'BANDIACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (388,'BANZAE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (389,'BARAUNAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (390,'BARCELOS DO SUL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (391,'BARRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (392,'BARRA DA ESTIVA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (393,'BARRA DO CHOCA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (394,'BARRA DO JACUIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (395,'BARRA DO MENDES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (396,'BARRA DO POJUCA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (397,'BARRA DO ROCHA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (398,'BARRA DO TARRACHIL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (399,'BARRACAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (400,'BARREIRAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (401,'BARRO ALTO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (402,'BARRO PRETO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (403,'BARRO VERMELHO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (404,'BARROCAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (405,'BASTIAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (406,'BATE PE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (407,'BATINGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (408,'BELA FLOR');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (409,'BELEM DA CACHOEIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (410,'BELMONTE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (411,'BELO CAMPO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (412,'BEM-BOM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (413,'BENDEGO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (414,'BENTO SIMOES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (415,'BIRITINGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (416,'BOA ESPERA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (417,'BOA NOVA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (418,'BOA UNIAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (419,'BOA VISTA DO LAGAMAR');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (420,'BOA VISTA DO TUPIM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (421,'BOACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (422,'BOCA DO CORREGO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (423,'BOM JESUS DA LAPA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (424,'BOM JESUS DA SERRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (425,'BOM SOSSEGO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (426,'BONFIM DA FEIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (427,'BONINAL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (428,'BONITO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (429,'BOQUIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (430,'BOTUPORA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (431,'BOTUQUARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (432,'BREJINHO DAS AMETISTAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (433,'BREJO DA SERRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (434,'BREJO LUIZA DE BRITO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (435,'BREJO NOVO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (436,'BREJOES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (437,'BREJOLANDIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (438,'BROTAS DE MACAUBAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (439,'BRUMADO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (440,'BUCUITUBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (441,'BUERAREMA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (442,'BURACICA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (443,'BURANHEM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (444,'BURIL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (445,'BURIS DE ABRANTES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (446,'BURITIRAMA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (447,'CAATIBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (448,'CABACEIRAS DO PARAGUACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (449,'CABRALIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (450,'CACHA PREGOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (451,'CACHOEIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (452,'CACHOEIRA DO MATO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (453,'CACULE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (454,'CAEM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (455,'CAETANOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (456,'CAETE-ACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (457,'CAETITE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (458,'CAFARNAUM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (459,'CAICARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (460,'CAIMBE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (461,'CAIRU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (462,'CAIUBI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (463,'CAJUI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (464,'CALDAS DO JORRO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (465,'CALDEIRAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (466,'CALDEIRAO GRANDE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (467,'CALDEIRAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (468,'CAMACAN');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (469,'CAMACARI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (470,'CAMAMU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (471,'CAMASSANDI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (472,'CAMIRIM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (473,'CAMPINHOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (474,'CAMPO ALEGRE DE LOURDES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (475,'CAMPO FORMOSO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (476,'CAMURUGI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (477,'CANABRAVINHA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (478,'CANAPOLIS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (479,'CANARANA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (480,'CANATIBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (481,'CANAVIEIRAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (482,'CANCHE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (483,'CANDEAL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (484,'CANDEIAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (485,'CANDIBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (486,'CANDIDO SALES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (487,'CANOAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (488,'CANSANCAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (489,'CANTO DO SOL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (490,'CANUDOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (491,'CAPAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (492,'CAPELA DO ALTO ALEGRE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (493,'CAPIM GROSSO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (494,'CARAGUATAI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (495,'CARAIBAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (496,'CARAIBUNA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (497,'CARAIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (498,'CARAIVA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (499,'CARAVELAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (500,'CARDEAL DA SILVA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (501,'CARINHANHA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (502,'CARIPARE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (503,'CARNAIBA DO SERTAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (504,'CARRAPICHEL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (505,'CASA NOVA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (506,'CASTELO NOVO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (507,'CASTRO ALVES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (508,'CATINGA DO MOURA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (509,'CATINGAL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (510,'CATOLANDIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (511,'CATOLES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (512,'CATOLEZINHO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (513,'CATU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (514,'CATU DE ABRANTES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (515,'CATURAMA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (516,'CAVUNGE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (517,'CENTRAL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (518,'CERAIMA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (519,'CHORROCHO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (520,'CICERO DANTAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (521,'CINCO RIOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (522,'CIPO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (523,'COARACI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (524,'COCOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (525,'COLONIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (526,'COMERCIO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (527,'CONCEICAO DA FEIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (528,'CONCEICAO DO ALMEIDA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (529,'CONCEICAO DO COITE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (530,'CONCEICAO DO JACUIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (531,'CONDE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (532,'CONDEUBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (533,'CONTENDAS DO SINCORA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (534,'COPIXABA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (535,'COQUEIROS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (536,'COQUINHOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (537,'CORACAO DE MARIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (538,'CORDEIROS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (539,'CORIBE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (540,'CORONEL JOAO SA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (541,'CORRENTINA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (542,'CORTA MAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (543,'COTEGIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (544,'COUTOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (545,'CRAVOLANDIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (546,'CRISOPOLIS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (547,'CRISTALANDIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (548,'CRISTOPOLIS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (549,'CRUSSAI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (550,'CRUZ DAS ALMAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (551,'CUMURUXATIBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (552,'CUNHANGI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (553,'CURACA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (554,'CURRAL FALSO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (555,'DARIO MEIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (556,'DELFINO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (557,'DESCOBERTO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (558,'DIAS COELHO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (559,'DIAS D AVILA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (560,'DIOGENES SAMPAIO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (561,'DOM BASILIO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (562,'DOM MACEDO COSTA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (563,'DONA MARIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (564,'DUAS BARRAS DO MORRO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (565,'ELISIO MEDRADO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (566,'ENCRUZILHADA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (567,'ENGENHEIRO FRANCA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (568,'ENGENHEIRO PONTES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (569,'ENTRE RIOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (570,'ERICO CARDOSO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (571,'ESPLANADA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (572,'EUCLIDES DA CUNHA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (573,'EUNAPOLIS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (574,'FATIMA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (575,'FEIRA DA MATA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (576,'FEIRA DE SANTANA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (577,'FERRADAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (578,'FILADELFIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (579,'FILANESIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (580,'FIRMINO ALVES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (581,'FLORESTA AZUL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (582,'FORMOSA DO RIO PRETO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (583,'FRANCA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (584,'GABIARRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (585,'GALEAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (586,'GAMBOA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (587,'GAMELEIRA DA LAPA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (588,'GAMELEIRA DO ASSURUA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (589,'GANDU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (590,'GAVIAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (591,'GENTIO DO OURO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (592,'GEOLANDIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (593,'GLORIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (594,'GONGOGI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (595,'GOVERNADOR JOAO DURVAL CARNEIRO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (596,'GOVERNADOR MANGABEIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (597,'GUAGIRUS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (598,'GUAI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (599,'GUAJERU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (600,'GUANAMBI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (601,'GUAPIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (602,'GUARAJUBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (603,'GUARATINGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (604,'GUEREM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (605,'GUINE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (606,'GUIRAPA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (607,'GURUPA MIRIM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (608,'HELIOPOLIS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (609,'HELVECIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (610,'HIDROLANDIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (611,'HUMILDES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (612,'IACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (613,'IBATUI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (614,'IBIACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (615,'IBIAJARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (616,'IBIAPORA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (617,'IBIASSUCE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (618,'IBICARAI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (619,'IBICOARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (620,'IBICUI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (621,'IBIPEBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (622,'IBIPETUM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (623,'IBIPITANGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (624,'IBIQUERA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (625,'IBIRABA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (626,'IBIRAJA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (627,'IBIRANHEM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (628,'IBIRAPITANGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (629,'IBIRAPUA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (630,'IBIRATAIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (631,'IBITIARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (632,'IBITIGUIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (633,'IBITIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (634,'IBITITA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (635,'IBITUNANE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (636,'IBITUPA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (637,'IBO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (638,'IBOTIRAMA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (639,'ICHU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (640,'ICO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (641,'IGAPORA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (642,'IGARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (643,'IGARITE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (644,'IGATU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (645,'IGRAPIUNA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (646,'IGUA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (647,'IGUAI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (648,'IGUAIBI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (649,'IGUATEMI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (650,'IGUIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (651,'IGUITU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (652,'ILHA DE MARE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (653,'ILHEUS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (654,'INDAI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (655,'INEMA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (656,'INHAMBUPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (657,'INHATA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (658,'INHAUMAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (659,'INHOBIM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (660,'INUBIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (661,'IPECAETA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (662,'IPIAU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (663,'IPIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (664,'IPIUNA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (665,'IPUCABA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (666,'IPUPIARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (667,'IRAJUBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (668,'IRAMAIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (669,'IRAPORANGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (670,'IRAQUARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (671,'IRARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (672,'IRECE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (673,'IRUNDIARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (674,'ITA-AZUL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (675,'ITABELA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (676,'ITABERABA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (677,'ITABUNA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (678,'ITACARE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (679,'ITACAVA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (680,'ITACHAMA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (681,'ITACIMIRIM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (682,'ITAETE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (683,'ITAGI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (684,'ITAGIBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (685,'ITAGIMIRIM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (686,'ITAGUACU DA BAHIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (687,'ITAIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (688,'ITAIBO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (689,'ITAIPU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (690,'ITAITU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (691,'ITAJAI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (692,'ITAJU DO COLONIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (693,'ITAJUBAQUARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (694,'ITAJUIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (695,'ITAJURU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (696,'ITAMARAJU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (697,'ITAMARI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (698,'ITAMBE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (699,'ITAMIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (700,'ITAMOTINGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (701,'ITANAGE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (702,'ITANAGRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (703,'ITANHEM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (704,'ITANHI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (705,'ITAPARICA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (706,'ITAPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (707,'ITAPEBI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (708,'ITAPEIPU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (709,'ITAPETINGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (710,'ITAPICURU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (711,'ITAPIREMA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (712,'ITAPITANGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (713,'ITAPORA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (714,'ITAPURA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (715,'ITAQUARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (716,'ITAQUARAI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (717,'ITARANTIM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (718,'ITATI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (719,'ITATIM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (720,'ITATINGUI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (721,'ITIRUCU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (722,'ITIUBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (723,'ITORORO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (724,'ITUACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (725,'ITUBERA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (726,'ITUPEVA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (727,'IUIU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (728,'JABORANDI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (729,'JACARACI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (730,'JACOBINA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (731,'JACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (732,'JACUIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (733,'JACURUNA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (734,'JAGUAQUARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (735,'JAGUARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (736,'JAGUARARI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (737,'JAGUARIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (738,'JAIBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (739,'JANDAIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (740,'JAPOMIRIM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (741,'JAPU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (742,'JAUA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (743,'JEQUIE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (744,'JEQUIRICA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (745,'JEREMOABO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (746,'JIRIBATUBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (747,'JITAUNA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (748,'JOAO AMARO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (749,'JOAO CORREIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (750,'JOAO DOURADO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (751,'JOSE GONCALVES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (752,'JUACEMA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (753,'JUAZEIRO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (754,'JUCURUCU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (755,'JUERANA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (756,'JUNCO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (757,'JUPAGUA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (758,'JURACI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (759,'JUREMAL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (760,'JUSSARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (761,'JUSSARI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (762,'JUSSIAPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (763,'KM SETE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (764,'LAFAIETE COUTINHO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (765,'LAGOA CLARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (766,'LAGOA DE MELQUIADES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (767,'LAGOA DO BOI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (768,'LAGOA GRANDE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (769,'LAGOA JOSE LUIS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (770,'LAGOA PRETA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (771,'LAGOA REAL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (772,'LAJE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (773,'LAJE DO BANCO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (774,'LAJEDAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (775,'LAJEDINHO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (776,'LAJEDO ALTO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (777,'LAJEDO DO TABOCAL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (778,'LAMARAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (779,'LAMARAO DO PASSE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (780,'LAPAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (781,'LARGO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (782,'LAURO DE FREITAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (783,'LENCOIS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (784,'LICINIO DE ALMEIDA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (785,'LIMOEIRO DO BOM VIVER');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (786,'LIVRAMENTO DO BRUMADO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (787,'LUCAIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (788,'LUIS VIANA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (789,'LUSTOSA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (790,'MACAJUBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (791,'MACARANI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (792,'MACAUBAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (793,'MACURURE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (794,'MADRE DE DEUS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (795,'MAETINGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (796,'MAIQUINIQUE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (797,'MAIRI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (798,'MALHADA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (799,'MALHADA DE PEDRAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (800,'MANDIROBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (801,'MANGUE SECO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (802,'MANIACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (803,'MANOEL VITORINO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (804,'MANSIDAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (805,'MANTIBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (806,'MAR GRANDE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (807,'MARACAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (808,'MARAGOGIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (809,'MARAGOGIPINHO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (810,'MARAU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (811,'MARCIONILIO SOUZA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (812,'MARCOLINO MOURA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (813,'MARIA QUITERIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (814,'MARICOABO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (815,'MARIQUITA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (816,'MASCOTE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (817,'MASSACARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (818,'MASSAROCA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (819,'MATA DA ALIANCA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (820,'MATA DE SAO JOAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (821,'MATARIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (822,'MATINA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (823,'MATINHA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (824,'MEDEIROS NETO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (825,'MIGUEL CALMON');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (826,'MILAGRES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (827,'MIMOSO DO OESTE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (828,'MINAS DO ESPIRITO SANTO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (829,'MINAS DO MIMOSO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (830,'MIRANDELA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (831,'MIRANGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (832,'MIRANGABA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (833,'MIRANTE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (834,'MOCAMBO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (835,'MOGIQUICABA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (836,'MONTE CRUZEIRO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (837,'MONTE GORDO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (838,'MONTE RECONCAVO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (839,'MONTE SANTO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (840,'MORPARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (841,'MORRINHOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (842,'MORRO DAS FLORES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (843,'MORRO DE SAO PAULO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (844,'MORRO DO CHAPEU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (845,'MORTUGABA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (846,'MUCUGE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (847,'MUCURI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (848,'MULUNGU DO MORRO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (849,'MUNDO NOVO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (850,'MUNIZ FERREIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (851,'MUQUEM DO SAO FRANCISCO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (852,'MURITIBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (853,'MUTAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (854,'MUTUIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (855,'NAGE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (856,'NARANDIBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (857,'NAZARE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (858,'NILO PECANHA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (859,'NORDESTINA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (860,'NOVA ALEGRIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (861,'NOVA BRASILIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (862,'NOVA CANAA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (863,'NOVA FATIMA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (864,'NOVA IBIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (865,'NOVA ITAIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (866,'NOVA ITARANA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (867,'NOVA LIDICE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (868,'NOVA REDENCAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (869,'NOVA SOURE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (870,'NOVA VICOSA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (871,'NOVO ACRE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (872,'NOVO HORIZONTE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (873,'NOVO TRIUNFO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (874,'NUCLEO RESIDENCIAL PILAR');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (875,'NUGUACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (876,'OLHOS D''AGUA DO SECO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (877,'OLHOS D''AGUA DO SERAFIM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (878,'OLINDINA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (879,'OLIVEIRA DOS BREJINHOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (880,'OLIVENCA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (881,'ONHA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (882,'ORIENTE NOVO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (883,'OURICANA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (884,'OURICANGAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (885,'OURICURI DO OURO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (886,'OUROLANDIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (887,'OUTEIRO REDONDO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (888,'PAIOL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (889,'PAJEU DO VENTO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (890,'PALAME');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (891,'PALMAS DE MONTE ALTO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (892,'PALMEIRAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (893,'PARAFUSO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (894,'PARAMIRIM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (895,'PARATECA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (896,'PARATINGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (897,'PARIPIRANGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (898,'PATAIBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (899,'PATAMUTE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (900,'PAU A PIQUE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (901,'PAU BRASIL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (902,'PAULO AFONSO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (903,'PE DE SERRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (904,'PEDRAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (905,'PEDRAS ALTAS DO MIRIM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (906,'PEDRO ALEXANDRE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (907,'PEIXE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (908,'PETIM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (909,'PIABANHA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (910,'PIATA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (911,'PICARRAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (912,'PILAO ARCADO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (913,'PIMENTEIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (914,'PINDAI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (915,'PINDOBACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (916,'PINHOES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (917,'PINTADAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (918,'PIRAGI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (919,'PIRAI DO NORTE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (920,'PIRAJA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (921,'PIRAJUIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (922,'PIRI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (923,'PIRIPA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (924,'PIRITIBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (925,'PITUBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (926,'PLANALTINO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (927,'PLANALTO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (928,'POCO CENTRAL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (929,'POCO DE FORA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (930,'POCOES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (931,'POCOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (932,'POJUCA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (933,'POLO PETROQUIMICO DE CAMACARI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (934,'PONTA DA AREIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (935,'PONTO NOVO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (936,'PORTO NOVO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (937,'PORTO SEGURO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (938,'POSTO DA MATA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (939,'POTIRAGUA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (940,'POXIM DO SUL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (941,'PRADO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (942,'PRESIDENTE DUTRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (943,'PRESIDENTE JANIO QUADROS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (944,'PRESIDENTE TANCREDO NEVES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (945,'PREVENIDO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (946,'QUARACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (947,'QUEIMADAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (948,'QUIJINGUE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (949,'QUIXABA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (950,'QUIXABEIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (951,'RAFAEL JAMBEIRO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (952,'RECIFE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (953,'REMANSO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (954,'REMEDIOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (955,'RETIROLANDIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (956,'RIACHAO DAS NEVES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (957,'RIACHAO DO JACUIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (958,'RIACHAO DO UTINGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (959,'RIACHO DA GUIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (960,'RIACHO DE SANTANA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (961,'RIACHO SECO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (962,'RIBEIRA DO AMPARO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (963,'RIBEIRA DO POMBAL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (964,'RIBEIRAO DO LARGO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (965,'RIBEIRAO DO SALTO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (966,'RIO DA DONA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (967,'RIO DE CONTAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (968,'RIO DO ANTONIO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (969,'RIO DO BRACO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (970,'RIO DO MEIO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (971,'RIO DO PIRES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (972,'RIO FUNDO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (973,'RIO REAL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (974,'RODELAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (975,'RUY BARBOSA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (976,'SALDANHA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (977,'SALGADALIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (978,'SALINAS DA MARGARIDA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (979,'SALOBRINHO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (980,'SALOBRO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (981,'SALVADOR');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (982,'SAMBAIBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (983,'SANTA BARBARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (984,'SANTA BRIGIDA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (985,'SANTA CRUZ CABRALIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (986,'SANTA CRUZ DA VITORIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (987,'SANTA INES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (988,'SANTA LUZIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (989,'SANTA MARIA DA VITORIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (990,'SANTA RITA DE CASSIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (991,'SANTA TEREZINHA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (992,'SANTALUZ');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (993,'SANTANA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (994,'SANTANA DO SOBRADO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (995,'SANTANOPOLIS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (996,'SANTIAGO DO IGUAPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (997,'SANTO AMARO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (998,'SANTO ANTONIO DE BARCELONA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (999,'SANTO ANTONIO DE JESUS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1000,'SANTO ESTEVAO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1001,'SANTO INACIO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1002,'SAO DESIDERIO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1003,'SAO DOMINGOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1004,'SAO FELIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1005,'SAO FELIX');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1006,'SAO FELIX DO CORIBE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1007,'SAO FRANCISCO DO CONDE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1008,'SAO GABRIEL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1009,'SAO GONCALO DOS CAMPOS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1010,'SAO JOAO DA FORTALEZA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1011,'SAO JOAO DA VITORIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1012,'SAO JOSE DA VITORIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1013,'SAO JOSE DO COLONIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1014,'SAO JOSE DO JACUIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1015,'SAO JOSE DO PRADO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1016,'SAO JOSE DO RIO GRANDE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1017,'SAO MIGUEL DAS MATAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1018,'SAO PAULINHO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1019,'SAO ROQUE DO PARAGUACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1020,'SAO SEBASTIAO DO PASSE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1021,'SAO TIMOTEO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1022,'SAPEACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1023,'SATIRO DIAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1024,'SAUBARA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1025,'SAUDAVEL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1026,'SAUDE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1027,'SEABRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1028,'SEBASTIAO LARANJEIRAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1029,'SENHOR DO BONFIM');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1030,'SENTO SE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1031,'SERGI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1032,'SERRA DA CANABRAVA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1033,'SERRA DO RAMALHO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1034,'SERRA DOURADA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1035,'SERRA GRANDE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1036,'SERRA PRETA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1037,'SERRINHA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1038,'SERROLANDIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1039,'SIMOES FILHO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1040,'SITIO DA BARAUNA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1041,'SITIO DO MATO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1042,'SITIO DO MEIO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1043,'SITIO DO QUINTO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1044,'SITIO GRANDE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1045,'SITIO NOVO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1046,'SOARES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1047,'SOBRADINHO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1048,'SOUTO SOARES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1049,'SUBAUMA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1050,'SUSSUARANA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1051,'TABOCAS DO BREJO VELHO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1052,'TABOLEIRO DO CASTRO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1053,'TABOQUINHAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1054,'TAGUA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1055,'TAMBURIL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1056,'TANHACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1057,'TANQUE NOVO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1058,'TANQUINHO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1059,'TANQUINHO DO POCO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1060,'TAPEROA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1061,'TAPIRAIPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1062,'TAPIRAMA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1063,'TAPIRAMUTA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1064,'TAPIRANGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1065,'TAPUIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1066,'TAQUARENDI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1067,'TAQUARINHA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1068,'TARTARUGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1069,'TAUAPE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1070,'TEIXEIRA DE FREITAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1071,'TEODORO SAMPAIO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1072,'TEOFILANDIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1073,'TEOLANDIA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1074,'TERRA NOVA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1075,'TIJUACU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1076,'TIQUARUCU');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1077,'TREMEDAL');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1078,'TRIUNFO DO SINCORA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1079,'TUCANO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1080,'UAUA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1081,'UBAIRA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1082,'UBAITABA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1083,'UBATA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1084,'UBIRACABA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1085,'UBIRAITA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1086,'UIBAI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1087,'UMBURANAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1088,'UMBUZEIRO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1089,'UNA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1090,'URANDI');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1091,'URUCUCA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1092,'UTINGA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1093,'VALE VERDE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1094,'VALENCA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1095,'VALENTE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1096,'VARZEA DA ROCA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1097,'VARZEA DO CALDAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1098,'VARZEA DO CERCO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1099,'VARZEA DO POCO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1100,'VARZEA NOVA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1101,'VARZEAS');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1102,'VARZEDO');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1103,'VELHA BOIPEBA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1104,'VENTURA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1105,'VERA CRUZ');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1106,'VEREDA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1107,'VILA DO CAFE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1108,'VITORIA DA CONQUISTA');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1109,'VOLTA GRANDE');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1110,'WAGNER');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1111,'WANDERLEY');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1112,'WENCESLAU GUIMARAES');
INSERT INTO tbl_municipalities (id_municipality,name) VALUES (1113,'XIQUE-XIQUE');
